#Pandas

In [1]:
import pandas as pd

C:\Users\djsce.student\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\compat\_optional.py:138: UserWarning: Pandas requires version '2.7.0' or newer of 'numexpr' (version '2.6.8' currently installed).
  warnings.warn(msg, UserWarning)

In [2]:
data = [10,20,30,'Jhon',50]
my_series = pd.Series(data)
print(my_series)  #default labelels 0,1,2

0      10
1      20
2      30
3    Jhon
4      50
dtype: object

In [3]:
print(my_series[2])

30

In [4]:
a = [1,3,5]
my_series = pd.Series(a,index = ["X","Y","Z"]);
print(my_series)

X    1
Y    3
Z    5
dtype: int64

In [5]:
print(my_series["X"])

1

In [6]:
grades = {"sem1":3.25,"sem2":3.28,"sem3":3.75}
my_grades = pd.Series(grades)  #We can use dictionary to give labels
print(my_grades)

sem1    3.25
sem2    3.28
sem3    3.75
dtype: float64

In [7]:
my_series = pd.Series(grades,index = ["sem1","sem2","sem4"])  #values not existing are already given NAn
print(my_series)

sem1    3.25
sem2    3.28
sem4     NaN
dtype: float64

#DataFrames

In [8]:
data = {"Name":["John","Alice","Bob"],
       "Age":[25,30,35],
       "City":["New York","London","Paris"]}
df = pd.DataFrame(data,index = [1,2,3])
print(df)

    Name  Age      City
1   John   25  New York
2  Alice   30    London
3    Bob   35     Paris

In [9]:
data = [["Alice",25,"New York"],
       ["John",30,"London"],
       ["Bob",35,"Paris"]]
df = pd.DataFrame(data,columns = ["Name","Age","City"])
print(df)  #data shall be entered properly else any value is entered anywhere

    Name  Age      City
0  Alice   25  New York
1   John   30    London
2    Bob   35     Paris

In [10]:
import numpy as np
data_array=  np.array([["ProductA",15.50,100],
                      ["ProductB",22.00,45],
                      ["ProductC",9.99,250]])
df = pd.DataFrame(data_array,columns = ["item","Price","stcok"])
print(df)

       item Price stcok
0  ProductA  15.5   100
1  ProductB  22.0    45
2  ProductC  9.99   250

In [11]:
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [12]:
import requests

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
response = requests.get(url)

with open('titanic.csv', 'wb') as f:
    f.write(response.content)

print('titanic.csv downloaded successfully.')

titanic.csv downloaded successfully.

In [13]:
df = pd.read_csv('titanic.csv')
display(df.head())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [14]:
print(df.shape)

(891, 12)

In [15]:
data = {"Name":["John","Alice","Bob"],
       "Age":[25,30,35],
       "City":["New York","London","Paris"]}
df = pd.DataFrame(data)
df.set_index("Name",inplace = True)
print(df) #treated as index not as column

       Age      City
Name
John    25  New York
Alice   30    London
Bob     35     Paris

In [16]:
data = {"Name":["John","Alice","Bob"],
       "Age":[25,30,35],
       "City":["New York","London","Paris"]}
df = pd.DataFrame(data,index = pd.RangeIndex(5,8,name = "index"))  # index cha name index...using range function for indices
print(df)

        Name  Age      City
index
5       John   25  New York
6      Alice   30    London
7        Bob   35     Paris

In [17]:
print(df.iloc[2])

Name      Bob
Age        35
City    Paris
Name: 7, dtype: object

In [18]:
data = {"Name":["John","Alice","Bob"],
       "Age":[25,30,35],
       "City":["New York","London","Paris"]}
df = pd.DataFrame(data)
print("Original df")
print(df)
#rename index
df.rename(index = {0:'A',1:'B',2:'C'},inplace = True)  #inplace = same data frame
print("Modified")
print(df)

#reset index
df.reset_index(inplace = True)
print("Reset")
print(df)

Original df
    Name  Age      City
0   John   25  New York
1  Alice   30    London
2    Bob   35     Paris
Modified
    Name  Age      City
A   John   25  New York
B  Alice   30    London
C    Bob   35     Paris
Reset
  index   Name  Age      City
0     A   John   25  New York
1     B  Alice   30    London
2     C    Bob   35     Paris

In [19]:
print(df.index)
print(df.index.values)

RangeIndex(start=0, stop=3, step=1)
[0 1 2]

In [20]:
arr=pd.array([1,2,3],dtype="Int64")
print(arr)

<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int64

In [21]:
s = pd.Series([1,2,3],index=["a","b","c"],dtype="Int64")
print(s)

a    1
b    2
c    3
dtype: Int64

In [22]:
pip install --upgrade pandas

The following command must be run outside of the IPython shell:

    $ pip install --upgrade pandas

The Python package manager (pip) can only be used from outside of IPython.
Please reissue the `pip` command in a separate terminal or command prompt.

See the Python documentation for more information on how to install packages:

    https://docs.python.org/3/installing/

In [23]:
string_array = pd.array(['apple','banana','cherry','date'],dtype='str')
print(string_array)
print()

<PandasArray>
['apple', 'banana', 'cherry', 'date']
Length: 4, dtype: str192

In [24]:
import pandas as pd
print("New Version:", pd.__version__)

arr = pd.array([1, 2, 3], dtype="Int64")
print(arr)

New Version: 1.3.5
<IntegerArray>
[1, 2, 3]
Length: 3, dtype: Int64

In [25]:
data = {
    'Name':['John','Alice','Bob','Emma','Mike','Sarah','David','Linda','Tom','Emily'],
    'Age':[25,30,35,28,32,27,40,33,29,31],
    'City':['New York','Paris','London','Sydney','Tokyo','Berlin','Rome','Madrid','Toronto','Moscow']
}
df=pd.DataFrame(data)
print(df)
print()
print(df.head(3))
print()
print(df.tail(3))

    Name  Age      City
0   John   25  New York
1  Alice   30     Paris
2    Bob   35    London
3   Emma   28    Sydney
4   Mike   32     Tokyo
5  Sarah   27    Berlin
6  David   40      Rome
7  Linda   33    Madrid
8    Tom   29   Toronto
9  Emily   31    Moscow

    Name  Age      City
0   John   25  New York
1  Alice   30     Paris
2    Bob   35    London

    Name  Age     City
7  Linda   33   Madrid
8    Tom   29  Toronto
9  Emily   31   Moscow

In [26]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
dtypes: int64(1), object(2)
memory usage: 368.0+ bytes

             Age
count  10.000000
mean   31.000000
std     4.320494
min    25.000000
25%    28.250000
50%    30.500000
75%    32.750000
max    40.000000

In [27]:
data = {
    'Name':['John','Emma','Michael','Sophia'],
    'Height':[5.5,6.0,5.8,5.3],
    'Qualification':['BSc','BBA','MBA','BSc']
}
df = pd.DataFrame(data)
print(df)
print()
address = ['New York','London','Sydney','Toronto']
df['Address']=address
print(df)

      Name  Height Qualification
0     John     5.5           BSc
1     Emma     6.0           BBA
2  Michael     5.8           MBA
3   Sophia     5.3           BSc

      Name  Height Qualification   Address
0     John     5.5           BSc  New York
1     Emma     6.0           BBA    London
2  Michael     5.8           MBA    Sydney
3   Sophia     5.3           BSc   Toronto

In [28]:
df.loc[len(df.index)]=['Amy',5.2,'BIT',None]
print(df)

      Name  Height Qualification   Address
0     John     5.5           BSc  New York
1     Emma     6.0           BBA    London
2  Michael     5.8           MBA    Sydney
3   Sophia     5.3           BSc   Toronto
4      Amy     5.2           BIT      None

In [29]:
df.drop(4,axis=0,inplace=True)
print(df)

      Name  Height Qualification   Address
0     John     5.5           BSc  New York
1     Emma     6.0           BBA    London
2  Michael     5.8           MBA    Sydney
3   Sophia     5.3           BSc   Toronto

In [30]:
df.drop([1,3],axis=0,inplace=True)
print(df)

      Name  Height Qualification   Address
0     John     5.5           BSc  New York
2  Michael     5.8           MBA    Sydney

In [31]:
data={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,35,40],
    'City':['New York','London','Paris','Tokyo'],
    'Height':['165','178','185','171'],
    'Profession':['Engineer','Entrepreneur','Unemployed','Actor'],
    'Marital Status':['Single','Marries','Divorced','Engaged']
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City Height    Profession Marital Status
0    Alice   25  New York    165      Engineer         Single
1      Bob   30    London    178  Entrepreneur        Marries
2  Charlie   35     Paris    185    Unemployed       Divorced
3    David   40     Tokyo    171         Actor        Engaged

In [32]:
df.drop('Age',axis=1,inplace=True)
print(df)

      Name      City Height    Profession Marital Status
0    Alice  New York    165      Engineer         Single
1      Bob    London    178  Entrepreneur        Marries
2  Charlie     Paris    185    Unemployed       Divorced
3    David     Tokyo    171         Actor        Engaged

In [33]:
df.drop(columns='Marital Status',inplace=True)
print(df)

      Name      City Height    Profession
0    Alice  New York    165      Engineer
1      Bob    London    178  Entrepreneur
2  Charlie     Paris    185    Unemployed
3    David     Tokyo    171         Actor

In [34]:
df.drop(['Height','Profession'],axis=1,inplace=True)
print(df)

      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo

In [35]:
data={
    'Name':['Alice','Bob','Charlie','David'],
    'Age':[25,30,35,40],
    'City':['New York','London','Paris','Tokyo']
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   35     Paris
3    David   40     Tokyo

In [36]:
df.rename(columns={'Name':'First_Name'},inplace=True)
print(df)

  First_Name  Age      City
0      Alice   25  New York
1        Bob   30    London
2    Charlie   35     Paris
3      David   40     Tokyo

In [37]:
df.rename(columns={'Age':'Number','City':'Address'},inplace=True)
print(df)

  First_Name  Number   Address
0      Alice      25  New York
1        Bob      30    London
2    Charlie      35     Paris
3      David      40     Tokyo

In [38]:
df.rename(index={0:7},inplace=True)
print(df)

  First_Name  Number   Address
7      Alice      25  New York
1        Bob      30    London
2    Charlie      35     Paris
3      David      40     Tokyo

In [39]:
data={
    'Name':['Alice','Bob','Charlie','David','Eve'],
    'Age':[25,30,35,40,18],
    'City':['New York','London','Paris','Tokyo','Sydney'],
    'Height':['165','178','185','171','179'],
    'Profession':['Engineer','Entrepreneur','Unemployed','Actor','Professor'],
    'Marital Status':['Single','Married','Divorced','Engaged','Single']
}
df = pd.DataFrame(data)
print(df)

      Name  Age      City Height    Profession Marital Status
0    Alice   25  New York    165      Engineer         Single
1      Bob   30    London    178  Entrepreneur        Married
2  Charlie   35     Paris    185    Unemployed       Divorced
3    David   40     Tokyo    171         Actor        Engaged
4      Eve   18    Sydney    179     Professor         Single

In [40]:
boolean_index=df.loc[df['Age']>30]
print("filtered Dataframe: ")
print(boolean_index)

filtered Dataframe:
      Name  Age   City Height  Profession Marital Status
2  Charlie   35  Paris    185  Unemployed       Divorced
3    David   40  Tokyo    171       Actor        Engaged

In [41]:
data = {'Name' : ['John','Emma','Michael','Sophia','Aadi'], 
        'Age' : [25,30,35,28,69],
        'City' : ['New York','Paris','London','Sydney','Kalyan']}
df = pd.DataFrame(data)
single_row = df.loc[2] #access a single row
print("single row:")
print(single_row)
print()
row_list = df.loc[[0,3,4]] #access rows 0, 3 and 4
print("list of rows:")
print(row_list)
print()
column_list = df.loc[:,['Name', 'Age']]
print("list of cols:")
print(column_list)
print()
specific_value = df.loc[1, 'Name']
print("specific value:")
print(specific_value)
print()

single row:
Name    Michael
Age          35
City     London
Name: 2, dtype: object

list of rows:
     Name  Age      City
0    John   25  New York
3  Sophia   28    Sydney
4    Aadi   69    Kalyan

list of cols:
      Name  Age
0     John   25
1     Emma   30
2  Michael   35
3   Sophia   28
4     Aadi   69

specific value:
Emma

In [42]:
data = {'Name' : ['John','Emma','Michael','Sophia','Aadi'], 
        'Age' : [25,30,35,28,69],
        'City' : ['New York','Paris','London','Sydney','Kalyan']}
df = pd.DataFrame(data)
slice_rows = df.loc[1:3] #slice row from index 1 to 3
print("slice rows:")
print(slice_rows)
print()
slice_cols = df.loc[:, ['Name', 'Age']] 
print("sliced columns:")
print(slice_cols)
print()

slice rows:
      Name  Age    City
1     Emma   30   Paris
2  Michael   35  London
3   Sophia   28  Sydney

sliced columns:
      Name  Age
0     John   25
1     Emma   30
2  Michael   35
3   Sophia   28
4     Aadi   69

In [47]:
df = pd.read_csv('titanic.csv')

In [50]:
print(df.head())
print()
print(df.tail())
print()
print(df.info())
print()
print(df.describe())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200